Return-Path: <foo.bar>
Received: from foo.bar ([123.123.123.123]) by
 mx.emig.kundenserver.de (mxeue010 [123.123.123.123]) with ESMTP (Nemesis) id
 1Mi3eL-1jFfKs35N3-00e3Lb for <crawx@crawx.crawx>; Mon, 15 Jun 2020
 19:57:16 +0200
Received: from 163.com () by mx.emig.kundenserver.de
 (mxeue111 ) with ESMTP (Nemesis) id 1M58C2-1jjE3S1oU0-001FOR
 for <someone@online.de>; Sun, 14 Jun 2020 06:10:58 +0200
Message-ID: <123.123.123.3397.rh@Alife12>
Date: Tue, 31 Dec 2105 23:59:59 +0100
From: =?UTF-8?B?TcKlIFLDqsOQIMOHw6XCp8Ovw7HDsA==?= <foo@blubbb>
MIME-Version: 1.0
X-RCPT-To: lilly
To: someone@online.de
Subject: =?UTF-8?B?TcKlIFLDqsOQIMOHw6XCp8Ovw7HDsA==?=
List-Unsubscribe: <mailto:leave-kv@foobar.com>
Content-Type: multipart/alternative; boundary="_----acMSMGjnNBLJ02nDjwgjBQ===_E8/58-47771-446577E5"
Content-Transfer-Encoding: quoted-printable
X-Spam-Flag: NO
Envelope-To: <crawx@crawx.crawx>
X-Spam-Flag: YES

Blubbbb

--_----acMSMGjnNBLJ02nDjwgjBQ===_E8/58-47771-446577E5
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset="UTF-8"

Blubbbb

--_----acMSMGjnNBLJ02nDjwgjBQ===_E8/58-47771-446577E5
Content-Type: text/html; charset="UTF-8"

Blubbbb


--_----acMSMGjnNBLJ02nDjwgjBQ===_E8/58-47771-446577E5--


Blubbbb