Content-Type: multipart/mixed;
 boundary=5da284b9d6ab81fbba0e56c702e94fd350aae1564cb329ee578007e73dc7
Mime-Version: 1.0
X-Spam-Status: X-Spam-Status: Yes, score=12.0
X-Spam-Flag: ************
X-Spam-Checker-Version: rspamd
Subject: Suchst du ein paar lustige Dates?
To: "go-imap-assassin" <go-imap-assassin@localhost>
From: "go-imap-assassin" <go-imap-assassin@localhost>
Date: Sun, 08 Nov 2020 12:32:21 +0100

--5da284b9d6ab81fbba0e56c702e94fd350aae1564cb329ee578007e73dc7
Content-Type: multipart/alternative;
 boundary=e45beb6fb1aa376f1178bc78909a03261abce7be1a63f7b8732a350f7268

--e45beb6fb1aa376f1178bc78909a03261abce7be1a63f7b8732a350f7268
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline
Content-Type: text/plain

rspamd has created the following report for the attached spam mail:

{"is_skipped":false,"score":12.021428,"required_score":15.0,"action":"add h=
eader","symbols":{"ARC_NA":{"name":"ARC_NA","score":0.0,"metric_score":0.0,=
"description":"ARC signature absent"},"HAS_REPLYTO":{"name":"HAS_REPLYTO","=
score":0.0,"metric_score":0.0,"description":"Has Reply-To header","options"=
:["mail@mail.adobe.com"]},"MID_RHS_MATCH_FROM":{"name":"MID_RHS_MATCH_FROM"=
,"score":0.0,"metric_score":0.0,"description":"Message-ID RHS matches From =
domain"},"FROM_HAS_DN":{"name":"FROM_HAS_DN","score":0.0,"metric_score":0.0=
,"description":"From header has a display name"},"HFILTER_URL_ONLY":{"name"=
:"HFILTER_URL_ONLY","score":1.571428,"metric_score":2.200000,"description":=
"URL only in body","options":["0.71428571428571"]},"RSPAMD_URIBL":{"name":"=
RSPAMD_URIBL","score":4.500000,"metric_score":4.500000,"description":"Rspam=
d uribl, bl.rspamd.com","options":["kutt.it:url"]},"HTML_SHORT_LINK_IMG_1":=
{"name":"HTML_SHORT_LINK_IMG_1","score":2.0,"metric_score":2.0,"description=
":"Short html part (0..1K) with a link to an image"},"REPLYTO_ADDR_EQ_FROM"=
:{"name":"REPLYTO_ADDR_EQ_FROM","score":0.0,"metric_score":0.0,"description=
":"Reply-To header is identical to SMTP From"},"TO_DN_NONE":{"name":"TO_DN_=
NONE","score":0.0,"metric_score":0.0,"description":"None of the recipients =
have display names"},"RCPT_COUNT_ONE":{"name":"RCPT_COUNT_ONE","score":0.0,=
"metric_score":0.0,"description":"One recipient","options":["1"]},"MANY_INV=
ISIBLE_PARTS":{"name":"MANY_INVISIBLE_PARTS","score":0.050000,"metric_score=
":1.0,"description":"Many parts are visually hidden","options":["1"]},"SUBJ=
ECT_ENDS_QUESTION":{"name":"SUBJECT_ENDS_QUESTION","score":1.0,"metric_scor=
e":1.0,"description":"Subject ends with a question"},"MIME_HTML_ONLY":{"nam=
e":"MIME_HTML_ONLY","score":0.200000,"metric_score":0.200000,"description":=
"Messages that have only HTML part"},"R_SPF_NA":{"name":"R_SPF_NA","score":=
0.0,"metric_score":0.0,"description":"Missing SPF record","options":["No do=
main"]},"RCVD_COUNT_ONE":{"name":"RCVD_COUNT_ONE","score":0.0,"metric_score=
":0.0,"description":"Message has one Received header","options":["1"]},"RCV=
D_NO_TLS_LAST":{"name":"RCVD_NO_TLS_LAST","score":0.100000,"metric_score":0=
.100000,"description":"Last hop did not use encrypted transports"},"DMARC_P=
OLICY_REJECT":{"name":"DMARC_POLICY_REJECT","score":2.0,"metric_score":2.0,=
"description":"DMARC reject policy","options":["mail.adobe.com : No valid S=
PF, No valid DKIM","reject"]},"R_DKIM_NA":{"name":"R_DKIM_NA","score":0.0,"=
metric_score":0.0,"description":"Missing DKIM signature"},"MIME_TRACE":{"na=
me":"MIME_TRACE","score":0.0,"metric_score":0.0,"options":["0:~"]},"ASN":{"=
name":"ASN","score":0.0,"metric_score":0.0,"options":["asn:396073, ipnet:45=
.148.9.0/24, country:US"]},"XM_CASE":{"name":"XM_CASE","score":0.500000,"me=
tric_score":0.500000,"description":"X-mailer .vs. X-Mailer"},"DATE_IN_PAST"=
:{"name":"DATE_IN_PAST","score":0.0,"metric_score":0.0},"ONCE_RECEIVED":{"n=
ame":"ONCE_RECEIVED","score":0.100000,"metric_score":0.100000,"description"=
:"One received header in a message"}},"messages":{},"urls":["i.imgur.com","=
kutt.it"],"emails":[],"message-id":"NM6036AECEE00055A6Aadobein_mid_prod9@ma=
il.adobe.com","time_real":0.767887,"milter":{"remove_headers":{"X-Spam":0}}=
}
--e45beb6fb1aa376f1178bc78909a03261abce7be1a63f7b8732a350f7268--

--5da284b9d6ab81fbba0e56c702e94fd350aae1564cb329ee578007e73dc7
Content-Disposition: attachment; filename=original-mail.eml
Content-Transfer-Encoding: binary
Content-Description: original message before rspamd
Content-Type: message/rfc822; x-spam-type=original

From: John Doe <jdoe@machine.example>
To: Mary Smith <mary@example.net>
Subject: Saying Hello
Date: Fri, 21 Nov 1997 09:55:06 -0600
Message-ID: <1234@local.machine.example>

This is a message just to say hello.
So, "Hello".
--5da284b9d6ab81fbba0e56c702e94fd350aae1564cb329ee578007e73dc7--
