name: go-imap-assassin lint, test and build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2.1.3

      - name: Generate code
        env:
          GO111MODULE: "off"
        run: |
          go get -u github.com/mjibson/esc
          go install github.com/mjibson/esc
          cd persistence/migrations
          export PATH=${PATH}:`go env GOPATH`/bin
          go generate

      - uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.32

      - name: Download dependencies
        run: |
          go mod download

      - name: Run tests
        run: |
          go test ./...

      - name: Build binary
        run: |
          go build
