name: build rspamd-go-imap-assassin

on:
  push:
    branches:
      - '*'
    paths:
      - 'docker/rspamd-go-imap-assassin/**'

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: docker/rspamd-go-imap-assassin
          file: docker/rspamd-go-imap-assassin/Dockerfile
          platforms: linux/386,linux/amd64,linux/ppc64le,linux/s390x,linux/arm/v7,linux/arm64
          push: true
          tags: crawxx/rspamd-go-imap-assassin:latest